// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupkg45mu8JkoWsbJso6deTOToZDJQAko',
    appId: '1:839797069567:web:e5ceaefd34bcf04d4adeca',
    messagingSenderId: '839797069567',
    projectId: 'bsems-851f2',
    authDomain: 'bsems-851f2.firebaseapp.com',
    storageBucket: 'bsems-851f2.firebasestorage.app',
    measurementId: 'G-C8QB4C9RQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6o9vC5MFfddA7EiDVZuDYL0RaGF_TnlE',
    appId: '1:839797069567:android:3e8b0a93065ecc824adeca',
    messagingSenderId: '839797069567',
    projectId: 'bsems-851f2',
    storageBucket: 'bsems-851f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNUH0b1DFz8KQeHrHWQZ-jdBdMku6yjY',
    appId: '1:839797069567:ios:83fe84eb9ce9b6244adeca',
    messagingSenderId: '839797069567',
    projectId: 'bsems-851f2',
    storageBucket: 'bsems-851f2.firebasestorage.app',
    iosBundleId: 'com.example.bsems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmNUH0b1DFz8KQeHrHWQZ-jdBdMku6yjY',
    appId: '1:839797069567:ios:83fe84eb9ce9b6244adeca',
    messagingSenderId: '839797069567',
    projectId: 'bsems-851f2',
    storageBucket: 'bsems-851f2.firebasestorage.app',
    iosBundleId: 'com.example.bsems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAupkg45mu8JkoWsbJso6deTOToZDJQAko',
    appId: '1:839797069567:web:292ba52d34f2cc9f4adeca',
    messagingSenderId: '839797069567',
    projectId: 'bsems-851f2',
    authDomain: 'bsems-851f2.firebaseapp.com',
    storageBucket: 'bsems-851f2.firebasestorage.app',
    measurementId: 'G-ESMCY05QDY',
  );
}
